### ISSUE TITLE
TablePlus: Error message

### ISSUE THREAD

**Issue by cmer** [rknightuk/alfred-workflows#9]
Whenever I type `tp`, I get this error in the debug console:

`The domain/default pair of (com.tinyapp.TablePlus, ViewSetting) does not exist (1)`

Obviously TablePlus is installed (via SetApp). Any idea?

**Comment by rknightuk** [comment]
I'm not sure on that - I don't have the Setapp version installed. It may be worth installing the original version of this that is PHP based https://github.com/chrisrenga/alfred-tableplus

I only built this version because I was on the MacOS beta without PHP but I believe this is going to be sorted before the new version comes out.

**Comment by cmer** [comment]
I think I figured out why it doesn't work, but I can't for the life of me figure out how to check if a directory exists in JXA. See:

```javascript
const setAppPaths = [
  "/Library/Application Support/com.tinyapp.TablePlus-setapp",
  "~/Library/Application Support/com.tinyapp.TablePlus-setapp"
];

let finderApp = Application("Finder");
let isSetApp = false;

for (let i = 0; i < setAppPaths.length; i++) {
  let path = setAppPaths[i];
  // THIS DOESN'T WORK!
  if (finderApp.exists(path)) {
    isSetApp = true;
    break;
  }
}

```

**Comment by rknightuk** [comment]
Closing, https://github.com/chrisrenga/alfred-tableplus works with the Setapp version
